### ISSUE TITLE
Diseño de logo y pantallas login/register

### ISSUE THREAD

**Issue by AntonioMC12** [ErTonix12/BookMaker#4]
Diseñar el logo de la aplicación así como las pantallas de login y register.

**Comment by alvaroolt** [comment]
Logo por aquí:

![Logo BookMaker v2](https://user-images.githubusercontent.com/36482489/144024019-11f9ca4b-d4b6-408a-bc2e-4f04e29074de.png)

**Comment by alvaroolt** [comment]
Paso el logo editado

Más ajustado:
![Logo BookMaker slim ](https://user-images.githubusercontent.com/36482489/144478267-05577504-8fc1-450e-88e5-47bd864bf8b4.jpeg)

Sin fondo: (pierde algo de calidad)
![Logo BookMaker transparente](https://user-images.githubusercontent.com/36482489/144478337-bbd5f780-b0bf-4f45-93fc-1bb57380e745.png)
